//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staj_Restoran_Projesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENULER
    {
        public long ID { get; set; }
        public long UYEID { get; set; }
        public decimal FIYAT { get; set; }
        public string ACIKLAMA { get; set; }
        public string RESIM { get; set; }
        public Nullable<int> SIRA { get; set; }
        public int MENUGRUBU { get; set; }
        public bool STATUS { get; set; }
        public System.DateTime KAYITTARIHI { get; set; }
        public Nullable<System.DateTime> GUNCELLEMETARIHI { get; set; }
    
        public virtual UYELER UYELER { get; set; }
    }
}
