//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staj_Restoran_Projesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UYELER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UYELER()
        {
            this.MENULER = new HashSet<MENULER>();
        }
    
        public long ID { get; set; }
        public string RESTAURANTADI { get; set; }
        public string KULLANICIEPOSTA { get; set; }
        public string KULLANICISIFRE { get; set; }
        public System.DateTime KAYITTARIHI { get; set; }
        public Nullable<System.DateTime> ONAYYARIHI { get; set; }
        public bool STATUS { get; set; }
        public System.Guid GUID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MENULER> MENULER { get; set; }
    }
}
